runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

# [START gae_flex_mailjet_yaml]
env_variables:
  MAILJET_API_KEY: YOUR-MAILJET-API-KEY
  MAILJET_SECRET_KEY: YOUR-MAILJET-SECRET-KEY
# [END gae_flex_mailjet_yaml]
